### ISSUE TITLE
problem with api web

### ISSUE THREAD

**Issue by felimoles** [xcesaralejandro/requeststorer#3]
i have a problem when use storearrival o web routes

solve it

**Comment by xcesaralejandro** [comment]
Fixed on [0.1.2](https://github.com/xcesaralejandro/requeststorer/releases/tag/0.1.2).  

The solution may not have been optimal, the data is completed with null because `Route::currentRouteAction()` does not provide the necessary information. Path names are kept reliable for tracing, consider always using them.
